### ISSUE TITLE
1. Implementation of create/store/view/delete functions

### ISSUE THREAD

**Issue by aligungr** [primetech495/RecipeJungle-Web#1]
User should be able to create/store/view/delete recipes from the web application. User can store the recipes and access them whenever needed to cook or start planning cooking.

Subissues for the web application:
- [x]  Creating the Recipe entity on the database (#8 )
- [x]  Implementation of the create function( #9  ) 
- [x]  Implementation of the store function( #10 ) 
- [x]  Implementation of the view function(#11 )
- [x]  Implementation of the delete function(#13 )
