### ISSUE TITLE
4. Implementation of photo recipe search by keyword

### ISSUE THREAD

**Issue by aligungr** [primetech495/RecipeJungle-Web#4]
User should be able to search photos with keywords to find recipes matching the given keywords (matching the recipe text or tags) so that user can access a recipe more easily.

Subissues of web application:
- [x]  Implementation of search bar(#19  )
- [x]  Implementation of search function(#22  )
- [x]  Implementation of search result page(#24 )
